"""Initial migration

Revision ID: e9cbd5a77c91
Revises:
Create Date: 2024-09-03 13:16:10.630041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9cbd5a77c91'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_date', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('date_of_death', sa.String(length=10), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=100),
               existing_nullable=False)

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isbn', sa.String(length=13), nullable=True))
        batch_op.add_column(sa.Column('publication_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=False))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.create_foreign_key('fk_author_id', 'author', ['author_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_constraint('fk_author_id', type_='foreignkey')
        batch_op.alter_column('title',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
        batch_op.drop_column('author_id')
        batch_op.drop_column('publication_year')
        batch_op.drop_column('isbn')

    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
        batch_op.drop_column('date_of_death')
        batch_op.drop_column('birth_date')

    # ### end Alembic commands ###
